### PR TITLE
Generate yaml info for bare format [renewed]

### PR DESCRIPTION
**Pull request by allcreater**
This is a continuation of the #75 request, refactored a bit to fulfill the [recommendations](https://github.com/floooh/sokol-tools/pull/75#issuecomment-1177704051).

I plan to add JSON output as well, and there are some thoughts on refactoring and removing code duplication between generators, but I think it's better to begin with minimum viable changes :)

### CODE REVIEW

**Comment by floooh** [comment]
Looks good, but can you fix the braces-style in yaml.cc please to be consistent with the rest of the code?

And also here (missing braces):

https://github.com/floooh/sokol-tools/pull/81/files#diff-75640e85ea0fbab9be41fb7e32068301a86d07e1c3fcb073645f40e6da23e890R110

**Comment by allcreater** [comment]
I did it :)

Also brought some "creativity" how the paths `file_path_vs` and `file_path_fs` are computed at `bare.cc` and `yaml.cc` - now the common part separated to a new variable for better readability (at least I hope so :)) 

Also naming of output file for yaml pass remaked a bit - now it's `{args.output}_[{module}_]reflection.yaml` instead of `{args.output}[_{module}].yaml`, additional word is proposed to make the name more unique as well as to disguise the underscore symbol that is produced by `mod_prefix` :) 

@kochol @floooh will be glad for your comments :)

**Comment by allcreater** [comment]
Just tested it on my shaders and two things were missing:
* flattened uniform blocks were displayed incorrectly
* uniform block's inst_name was unavailable

I added it to the last commit, and now it (looks like) contains enough data for practical use.

Please advise if there is anything else I could do :)

**Comment by allcreater** [comment]
Hi @floooh, so sorry to disturb you, what are you think about this PR? Can I do anything else to improve it? :)

**Comment by floooh** [comment]
Nothing wrong with the PR, I just need to find some time to catch up with PRs.

**Comment by floooh** [comment]
Ok, merged, thanks for the PR! The text for --help was missing the bare_yaml format, I added that (also I wonder why this PR didn't trigger a GH Actions build, hmmm...).

I'll also trigger a Deployment GH Action, so that the binaries in sokol-tools-bin are updated.

**Comment by floooh** [comment]
....how did you actually create this PR? I just noticed that the related PR https://github.com/floooh/sokol-tools/pull/75 was automatically closed to. Is it possible on Github to link two PRs somehow?

**Comment by allcreater** [comment]
@floooh thank you very much for your attention!

Well, as far as I remember, I just checked out the @kochol branch, added a few commits, and created a new branch from it, all done from the Git command line. I believe that when merging branches, GitHub simply checks for PR commits on the target branch.

**Pull request merged**
