### PR TITLE
sokol-d: initial support

### PR DESCRIPTION
**Pull request by kassane**
cc: @floooh

solve:
- https://github.com/kassane/sokol-d/issues/4

Result: https://github.com/kassane/sokol-d/commit/5b01ba414bcbb9f64a58a2d9ad80ce51134adba7

### CODE REVIEW

**Comment by kassane** [comment]
Wow!!

**Change:**
```cpp
std::filesystem::path module_prefix = args.input;
L("module shaders.{};\n", module_prefix.stem().c_str());
```
### Errors

**MacOS**
```bash
/Users/runner/work/sokol-tools/sokol-tools/src/shdc/sokold.cc:461:22: error: 'path' is unavailable: introduced in macOS 10.15
    std::filesystem::path module_prefix = args.input;
                     ^
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/filesystem:909:24: note: 'path' has been explicitly marked unavailable here
```

**Windows-MSVC**
```bash
D:\a\sokol-tools\sokol-tools\ext\fmt\include\fmt\core.h(2530,46): error C2039: 'parse': is not a member of 'fmt::v10::formatter<const std::filesystem::path::value_type *,Char,void>' [D:\a\sokol-tools\fips-build\sokol-tools\win64-vstudio-debug\src\shdc\sokol-shdc.vcxproj]
          with
          [
              Char=char
          ] (compiling source file D:\a\sokol-tools\sokol-tools\src\shdc\sokold.cc)
D:\a\sokol-tools\sokol-tools\ext\fmt\include\fmt\core.h(1704,48): message : see declaration of 'fmt::v10::formatter<const std::filesystem::path::value_type *,Char,void>' [D:\a\sokol-tools\fips-build\sokol-tools\win64-vstudio-debug\src\shdc\sokol-shdc.vcxproj]
```

**Comment by kassane** [comment]
Done. Await review!!

**Comment by floooh** [comment]
Ah, a bit tricky to keep track of the various discussion threads :smile: See my reply here:

https://github.com/kassane/sokol-d/issues/5#issuecomment-1875665075

**Comment by kassane** [comment]
When merge #120 it will be necessary to refactor this D lang support proposal.

**Comment by floooh** [comment]
Yes, I'm currently changing the entire structure of sokol-shdc, but one goal is to make it easier to add new language outputs.

**Comment by floooh** [comment]
Note: this PR has rotted since I completely changed the sokol-tools file structure. I'll take care of that on my side, and while at I'll also try to get all the other sokol-d things done.

**Comment by floooh** [comment]
Closing in favour of https://github.com/floooh/sokol-tools/pull/128

**Pull request closed without merging**
